# Generated by Django 5.2.17 on 2026-08-05 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_email', models.EmailField(max_length=254, unique=True)),
                ('encrypted_data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google credential',
                'verbose_name_plural': 'Google credentials',
            },
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ike', 'Ike'), ('wife', 'Wife'), ('child', 'Child'), ('other', 'Other')], default='other', max_length=20)),
                ('authorised', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IncomingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(max_length=64, unique=True)),
                ('gmail_thread_id', models.CharField(blank=True, default='', max_length=64)),
                ('outer_sender', models.EmailField(help_text='Address that actually sent/forwarded the email to us.', max_length=254)),
                ('recipients', models.TextField(blank=True, default='')),
                ('subject', models.CharField(blank=True, default='', max_length=998)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html_sanitised', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('is_forwarded', models.BooleanField(default=False)),
                ('original_forwarded_sender', models.EmailField(blank=True, default='', max_length=254)),
                ('original_forwarded_date', models.DateTimeField(blank=True, null=True)),
                ('has_attachments', models.BooleanField(default=False)),
                ('attachment_metadata', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('pending_review', 'Pending review'), ('failed', 'Failed'), ('unauthorised', 'Unauthorised')], default='received', max_length=20)),
                ('processing_attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(blank=True, default='', max_length=100)),
                ('object_id', models.CharField(blank=True, default='', max_length=100)),
                ('success', models.BooleanField(default=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.incomingemail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create_calendar_event', 'Create calendar event'), ('requires_review', 'Requires review'), ('unsupported', 'Unsupported')], max_length=30)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('meeting_url', models.URLField(blank=True, default='', max_length=1000)),
                ('organiser', models.CharField(blank=True, default='', max_length=255)),
                ('booking_reference', models.CharField(blank=True, default='', max_length=255)),
                ('confidence', models.FloatField(default=0.0)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('ambiguity_notes', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('executed', 'Executed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='proposed', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('duplicate_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incoming_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_actions', to='core.incomingemail')),
                ('related_household_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_actions', to='core.householdmember')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEventRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(max_length=255)),
                ('calendar_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Europe/London', max_length=64)),
                ('all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('booking_reference', models.CharField(blank=True, default='', max_length=255)),
                ('duplicate_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incoming_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.incomingemail')),
                ('parsed_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.parsedaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
