# Generated by Django 5.2.17 on 2026-08-05 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedaction',
            name='assigned_to',
            field=models.CharField(blank=True, choices=[('ike', 'Ike'), ('wife', 'Wife'), ('both', 'Both'), ('unassigned', 'Unassigned')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='parsedaction',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='parsedaction',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parsedaction',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parsedaction',
            name='note_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='parsedaction',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parsedaction',
            name='reminder_lead_days',
            field=models.PositiveIntegerField(blank=True, help_text="Set only when the user said something like 'the day before the event'. The actual reminder date is always computed in Python from the validated event date, never trusted from the model.", null=True),
        ),
        migrations.AddField(
            model_name='parsedaction',
            name='reminder_recipient',
            field=models.CharField(blank=True, choices=[('ike', 'Ike'), ('wife', 'Wife'), ('both', 'Both')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='parsedaction',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parsedaction',
            name='task_search_text',
            field=models.CharField(blank=True, default='', help_text='Free text used to look up an existing task for mark_task_complete.', max_length=500),
        ),
        migrations.AlterField(
            model_name='parsedaction',
            name='action_type',
            field=models.CharField(choices=[('create_calendar_event', 'Create calendar event'), ('create_task', 'Create task'), ('create_note', 'Create note'), ('create_email_reminder', 'Create email reminder'), ('mark_task_complete', 'Mark task complete'), ('requires_review', 'Requires review'), ('unsupported', 'Unsupported')], max_length=30),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_household_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='core.householdmember')),
                ('source_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='core.incomingemail')),
                ('source_parsed_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='core.parsedaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('assigned_to', models.CharField(choices=[('ike', 'Ike'), ('wife', 'Wife'), ('both', 'Both'), ('unassigned', 'Unassigned')], default='unassigned', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='core.householdmember')),
                ('source_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.incomingemail')),
                ('source_parsed_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.parsedaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('recipient', models.CharField(choices=[('ike', 'Ike'), ('wife', 'Wife'), ('both', 'Both')], max_length=10)),
                ('reminder_date', models.DateField()),
                ('reminder_time', models.TimeField()),
                ('timezone', models.CharField(default='Europe/London', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('send_key', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('rfc_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('delivery_attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_calendar_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='core.calendareventrecord')),
                ('source_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='core.incomingemail')),
                ('source_parsed_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='core.parsedaction')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='core.task')),
            ],
            options={
                'ordering': ['reminder_date', 'reminder_time'],
            },
        ),
    ]
