# Generated by Django 5.2.17 on 2026-08-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parsedaction_assigned_to_parsedaction_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendareventrecord',
            name='recurrence_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='calendareventrecord',
            name='recurrence_rule',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='parsedaction',
            name='recurrence_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parsedaction',
            name='recurrence_days_of_week',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='parsedaction',
            name='recurrence_frequency',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='parsedaction',
            name='recurrence_interval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parsedaction',
            name='recurrence_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
