# Generated by Django 5.2.17 on 2026-08-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_calendareventrecord_recurrence_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedaction',
            name='notify_both',
            field=models.BooleanField(default=False),
        ),
    ]
