# Generated by Django 5.2.17 on 2026-08-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_parsedaction_notify_both"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramChat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chat_id", models.BigIntegerField(unique=True)),
                ("chat_type", models.CharField(choices=[("private", "Private"), ("group", "Group"), ("supergroup", "Supergroup")], max_length=20)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("authorised", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["chat_type", "chat_id"]},
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.BigIntegerField(unique=True)),
                ("role", models.CharField(choices=[("ike", "Ike"), ("wife", "Wife"), ("child", "Child"), ("other", "Other")], max_length=20)),
                ("username", models.CharField(blank=True, default="", max_length=64)),
                ("display_name", models.CharField(blank=True, default="", max_length=255)),
                ("authorised", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["role", "user_id"]},
        ),
        migrations.AddField(
            model_name="incomingemail",
            name="source",
            field=models.CharField(choices=[("email", "Email"), ("telegram", "Telegram")], default="email", max_length=20),
        ),
        migrations.CreateModel(
            name="TelegramUpdate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("update_id", models.BigIntegerField(unique=True)),
                ("update_type", models.CharField(blank=True, default="", max_length=30)),
                ("processed", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("chat", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updates", to="core.telegramchat")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updates", to="core.telegramuser")),
            ],
            options={"ordering": ["-update_id"]},
        ),
        migrations.CreateModel(
            name="TelegramConversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("awaiting_clarification", "Awaiting clarification"), ("awaiting_confirmation", "Awaiting confirmation"), ("executing", "Executing"), ("completed", "Completed"), ("cancelled", "Cancelled"), ("failed", "Failed")], default="awaiting_clarification", max_length=30)),
                ("transcript", models.JSONField(blank=True, default=list)),
                ("draft_extraction", models.JSONField(blank=True, default=dict)),
                ("clarification_count", models.PositiveSmallIntegerField(default=0)),
                ("last_bot_message_id", models.BigIntegerField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("chat", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="conversations", to="core.telegramchat")),
                ("incoming_email", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="telegram_conversation", to="core.incomingemail")),
                ("parsed_action", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="telegram_conversation", to="core.parsedaction")),
                ("requested_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="conversations", to="core.telegramuser")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["chat", "status"], name="core_telegr_chat_id_634368_idx")],
            },
        ),
    ]
