# Generated by Django 5.2.17 on 2026-08-08 18:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_telegramchat_telegramuser_incomingemail_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('briefing_enabled', models.BooleanField(default=True)),
                ('briefing_time', models.TimeField(default=datetime.time(7, 30))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='core.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramBriefingDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('briefing_date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefing_deliveries', to='core.telegramuser')),
            ],
            options={
                'ordering': ['-briefing_date', '-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'briefing_date'), name='telegram_one_briefing_per_day')],
            },
        ),
        migrations.CreateModel(
            name='TelegramInboxAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('edit_note', 'Edit note'), ('edit_task', 'Edit task'), ('reschedule_event', 'Reschedule event'), ('cancel_event', 'Cancel event'), ('set_briefing_time', 'Set briefing time')], max_length=30)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('awaiting_input', 'Awaiting input'), ('awaiting_confirmation', 'Awaiting confirmation'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='awaiting_input', max_length=30)),
                ('proposed_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_actions', to='core.telegramchat')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbox_actions', to='core.telegramuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chat', 'requested_by', 'status'], name='core_telegr_chat_id_f0925e_idx')],
            },
        ),
    ]
