# Generated by Django 5.2.17 on 2026-08-09

import django.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_telegrampreference_telegrambriefingdelivery_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatchworkShift",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_uid", models.CharField(max_length=512, unique=True)),
                ("google_event_id", models.CharField(blank=True, default="", max_length=255)),
                ("calendar_id", models.CharField(blank=True, default="", max_length=255)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("timezone", models.CharField(default="Europe/London", max_length=64)),
                ("all_day", models.BooleanField(default=False)),
                ("source_status", models.CharField(blank=True, default="", max_length=50)),
                ("payload_hash", models.CharField(blank=True, default="", max_length=64)),
                ("active", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["starts_at", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="patchworkshift",
            index=models.Index(fields=["active", "starts_at"], name="core_patchw_active_36b68e_idx"),
        ),
    ]
