# Generated by Django 5.2.17 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_patchworkshift"),
    ]

    operations = [
        migrations.AddField(
            model_name="patchworkshift",
            name="source_label",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="patchworkshift",
            name="suppressed",
            field=models.BooleanField(default=False),
        ),
    ]
